In [1]:
!pip install spotipy

zsh:1: /usr/local/bin/pip: bad interpreter: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: no such file or directory
Collecting spotipy
  Downloading spotipy-2.21.0-py3-none-any.whl (28 kB)
Requirement already satisfied: six>=1.15.0 in /Users/rnp/Library/Python/3.9/lib/python/site-packages (from spotipy) (1.16.0)
Collecting requests>=2.25.0
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 1.5 MB/s eta 0:00:00
Collecting urllib3>=1.26.0
  Downloading urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.4/140.4 kB 3.0 MB/s eta 0:00:00a 0:00:01
Collecting redis>=3.5.3
  Downloading redis-4.3.4-py3-none-any.whl (246 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 246.2/246.2 kB 5.1 MB/s eta 0:00:0000:01
Requirement already satisfied: packaging>=20.4 in /Users/rnp/Library/Python/3.9/lib/python/site-packages (from redis>=3.5.3->spotipy) (21.3)
Collecting async-timeout>=4.0.2
  Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting deprecated>=1.2.3
  Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Collecting charset-normalizer<3,>=2
  Downloading charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting idna<4,>=2.5
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 2.3 MB/s eta 0:00:00
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from requests>=2.25.0->spotipy) (2022.6.15.2)
Collecting wrapt<2,>=1.10
  Downloading wrapt-1.14.1-cp39-cp39-macosx_10_9_x86_64.whl (35 kB)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Users/rnp/Library/Python/3.9/lib/python/site-packages (from packaging>=20.4->redis>=3.5.3->spotipy) (3.0.9)
Installing collected packages: wrapt, urllib3, idna, charset-normalizer, async-timeout, requests, deprecated, redis, spotipy
Successfully installed async-timeout-4.0.2 charset-normalizer-2.1.1 deprecated-1.2.13 idna-3.4 redis-4.3.4 requests-2.28.1 spotipy-2.21.0 urllib3-1.26.12 wrapt-1.14.1

[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: pip3 install --upgrade pip

In [5]:
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
cid = 'd3e048fac0e8438cab168ac60459044c'
secret = '4d47925e9199481fb41cc0c1406de938'
client_credentials_manager = SpotifyClientCredentials(
    client_id=cid, client_secret=secret)
sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)

In [10]:
artist_name = []
track_name = []
popularity = []
track_id = []
for i in range(0, 50, 1):
    track_results = sp.search(q='year:2018', type='track', limit=50, offset=i)
    for i, t in enumerate(track_results['tracks']['items']):
        artist_name.append(t['artists'][0]['name'])
        track_name.append(t['name'])
        track_id.append(t['id'])
        popularity.append(t['popularity'])

In [11]:
import pandas as pd
track_dataframe = pd.DataFrame(
    {'artist_name': artist_name, 'track_name': track_name, 'track_id': track_id, 'popularity': popularity})
print(track_dataframe.shape)
track_dataframe.head()

(2500, 4)

,artist_name,track_name,track_id,popularity
0,Morgan Wallen,Whiskey Glasses,6foY66mWZN0pSRjZ408c00,80
1,Lil Baby,Drip Too Hard (Lil Baby & Gunna),78QR3Wp35dqAhFEc2qAGjE,84
2,Lil Baby,Yes Indeed,6vN77lE9LK6HP2DewaN6HZ,82
3,The Weeknd,I Was Never There,1cKHdTo9u0ZymJdPGSh6nq,89
4,Joji,SLOW DANCING IN THE DARK,0rKtyWc8bvkriBthvHKY8d,84

In [15]:
track_dataframe.sort_values(by=['popularity'], ascending=False)[
    ['track_name', 'artist_name']].head(20)

               track_name    artist_name
150     I Was Never There     The Weeknd
3       I Was Never There     The Weeknd
52      I Was Never There     The Weeknd
101     I Was Never There     The Weeknd
54       Call Out My Name     The Weeknd
257  lovely (with Khalid)  Billie Eilish
110  lovely (with Khalid)  Billie Eilish
355  lovely (with Khalid)  Billie Eilish
250      Call Out My Name     The Weeknd
453  lovely (with Khalid)  Billie Eilish
103      Call Out My Name     The Weeknd
306  lovely (with Khalid)  Billie Eilish
502  lovely (with Khalid)  Billie Eilish
208  lovely (with Khalid)  Billie Eilish
600  lovely (with Khalid)  Billie Eilish
12   lovely (with Khalid)  Billie Eilish
61   lovely (with Khalid)  Billie Eilish
159  lovely (with Khalid)  Billie Eilish
551  lovely (with Khalid)  Billie Eilish
152      Call Out My Name     The Weeknd

In [16]:

by_art_fol = pd.DataFrame(track_dataframe.sort_values(by=['artist_followers'], ascending=False)[
                          ['artist_followers', 'artist_popularity', 'artist_name', 'artist_genres']])
by_art_fol.astype(str).drop_duplicates().head(20)

NameError: name 'track_df' is not defined